### ISSUE TITLE
How to get the audio samples from generated buffer

### ISSUE THREAD

**Issue by happyTonakai** [nwhitehead/tinysoundfont-pybind#1]
I'm loading a midi file and want to get the audio samples for further processing in python, but I got all zeros in the buffer.

```py
import numpy as np
import tinysoundfont

synth = tinysoundfont.Synth()
sfid = synth.sfload("FluidR3_GM.sf2")

seq = tinysoundfont.Sequencer(synth)
seq.midi_load("1080-c01.mid")

# Larger buffer because latency is not important
# synth.start(buffer_size=4096)

buffer = synth.generate(441000)  # get 10 seconds buffer
block = np.frombuffer(bytes(buffer), dtype=np.float32)

print(block.max(), block.min())  # all samples are zero
```

I dunno what is happening... All samples in the buffer are zero. `bytes(buffer) = b'\x00\x00\x00\x00\x00\x00\x00\x00'`... 

 In your another great package `pyfluidsynth`, there is a method `get_samples(len)` which satisfies my requirement but I didn't figure out how to load a midi file with that package.

**Comment by amberwhitehead** [comment]
@happyTonakai Thank you for reporting this! The issue was that calling `generate` wasn't calling the sequencer callback function to advance time. So it would work if you did your own `noteon` and such but not for MIDI files. I reworked the code so calling `generate` now _does_ call the sequencer callback. With the new version your code should show not just zeros in the numpy block.

Let me know if it works or doesn't work for you.
